services:
  tests: &app
    build: &app-build
      context: .
      dockerfile: Dockerfile
      target: testing
      args:
        DEVELOPER_UID: ${UID:-1002}
        DEVELOPER_USERNAME: ${USER:-you}
    image: icalialabs/lithia-converter-backend${TESTING_IMAGE_TAG:-:testing}
    volumes:
      - .:/workspaces/lithia-converter-backend
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    entrypoint: python ./tests/test_config.py
    environment: &app-env
      # ENV variables for the app
      ENV_STATUS: testing

  devcontainer:
    <<: *app
    build:
      <<: *app-build
      target: development
    volumes:
      - .:/workspaces/lithia-converter-backend
    image: icalialabs/lithia-converter-backend:development
    entrypoint: /bin/zsh -c "while sleep 1000; do :; done"
    environment:
      <<: *app-env
      EDITOR: code --wait

  deployment:
    <<: *app
    build:
      <<: *app-build
      target: production
    ports:
      - published: ${LITHIA_CONVERTER:-8080}
        target: 8080
    environment:
      <<: *app-env
